name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy-3.10"]
        django-version: ["3.2", "4.2", "5.0", "5.1"]
        experimental: [false]
        include:
          - python-version: "3.12"
            django-version: "packaging"
            experimental: false
          - python-version: "3.12"
            django-version: "main"
            experimental: true
        exclude:
          # Unsupported Python versions for Django 5.0
          - python-version: "3.8"
            django-version: "5.0"
          - python-version: "3.9"
            django-version: "5.0"
          # Unsupported Python versions for Django 5.1
          - python-version: "3.8"
            django-version: "5.1"
          - python-version: "3.9"
            django-version: "5.1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install -U pip Django~=${{ matrix.django-version }} djangorestframework
          python -m pip freeze
